name: build

on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/build.yml
      - lib/**
      - pubspec.yaml


env:
  # update with the name of the main binary
  binary: web
  add_binaries_to_github_release: true

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
          architecture: x64 # optional, x64 or arm64
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build web --release

      - name: Package as a zip
        working-directory: ./build/web
        run: |
          zip --recurse-paths ../../${{ env.binary }}.zip .

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.binary }}.zip
          name: web

      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Upload binaries to release
        if: ${{ env.add_binaries_to_github_release == 'true' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.binary }}.zip
          asset_name: ${{ env.binary }}-${{ env.RELEASE_DATE }}.zip
          tag: ${{ env.RELEASE_DATE }}
          overwrite: true